### ISSUE TITLE
Project Still Active?

### ISSUE THREAD

**Issue by svpernova09** [allmyitjason/codeception-selenium-ide-format#2]
Hi! Thanks for your awesome work on this. I'm wondering if it's still active. I'd love to get some updates rolling but wanted to check with you before I forked it myself and submitted it to the addons library.

Thanks!

**Comment by sp0tteh** [comment]
Hey,

Will accept pull requests ect and happy to add new members to the project to keep it up to date! Cheers

**Comment by svpernova09** [comment]
Great! Thanks

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org
